<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DefineConstants>ENABLE_GENERATOR_INFO</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
      <PackageReference Include="Moonad" Version="5.5.1" />
      <PackageReference Include="Moonad.Next" Version="1.0.0" />
    </ItemGroup>

</Project>
